### ISSUE TITLE
搜索结果无法点击

### ISSUE THREAD

**Issue by rongfengfang** [Joker-388/JKRCustomSearchController#1]
在JKRSearchResultViewController中添加- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath方法，可是却不起作用，是否有哪个地方限制了？

**Comment by Joker-388** [comment]
因为那个resultView并不属于searchController，而是自定义的结果展示页面，需要自己来实现内部的展示和逻辑处理。searchController只是通知resultView刷新而已。这个和系统的searchController是一样的。

**Comment by Joker-388** [comment]
应该是响应链传递被我阻断了，我有时间再看看

**Comment by lkpHub** [comment]
哥们呀，能不能帮忙看下tableview的点击事件执行不了！

**Comment by Joker-388** [comment]
Fix bug: SearchResultViewController can not touch.

**Comment by Joker-388** [comment]
这个bug刚刚解决了，同步一下代码就可以。

**Comment by lkpHub** [comment]
好的，我去试试！
