### ISSUE TITLE
跳转不了新的界面

### ISSUE THREAD

**Issue by lkpHub** [Joker-388/JKRCustomSearchController#2]
大神你好，我试了下，可以点击了，然后我想点击的时候push到一个新的界面，我用testviewcontroller进行了测试，不知道为啥代码走了，但是没有push到新的界面呀

**Comment by Joker-388** [comment]
因为这个界面本来就没有在导航控制器中，我是通过直接addSubView添加到跟视图中的。
你可以通过presentViewController:这个方法来跳转，代码我刚刚跟新上去了，可以在ResultViewController中tableView的cell点击回调中看到。

**Comment by lkpHub** [comment]
嗯嗯，谢谢大神了，我发现我的项目中我弄复杂了，真是蛋疼！

**Comment by gsj602** [comment]
搜索的时候，搜索框上移，  但是搜索框searchbar是原来控制器的view上的 tableview 的头视图 tableviewheader，所以此时虽然位置很小，但是依然可以向上滚动，然后搜索框就飞到天上去了，显露出了原来的 tableview，可以用模拟器鼠标测试。是个小 bug  在代理方法中分别加入 self.tableview.scorllEndabled=NO;和 YES。可以解决。  但是我其实认真看，searchBar是什么时候怎么上移的呀？
