### ISSUE TITLE
界面小 bug 搜索框飞上天

### ISSUE THREAD

**Issue by gsj602** [Joker-388/JKRCustomSearchController#3]
搜索的时候，搜索框上移， 但是搜索框searchbar是原来控制器的view上的 tableview 的头视图 tableviewheader，所以此时虽然位置很小，但是依然可以向上滚动，然后搜索框就飞到天上去了，显露出了原来的 tableview，可以用模拟器鼠标测试。是个小 bug 在代理方法中分别加入 self.tableview.scorllEndabled=NO;和 YES。可以解决。 但是我其实认真看，searchBar是什么时候怎么上移的呀？

**Comment by Joker-388** [comment]
@gsj602 已经解决这个问题
